	double coefTemp[MixDim];
	double expmatrix[N][MixDim];
	double expmatrixmax[N];
	double normProb[N][MixDim];
	double mixnormProb[N];
	double postProb[N][MixDim];
	double sumPostProb[MixDim];
	double sumPostProb1[MFCCDim][MixDim];
	double sumPostProb2[MixDim][MFCCDim];